# Generated by Django 5.2.6 on 2025-10-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0003_rename_calories_dietplan_total_calories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('operating_hours', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Gym Information',
                'verbose_name_plural': 'Gym Information',
            },
        ),
    ]
