# Generated by Django 5.2.6 on 2025-10-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0004_gyminfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietday',
            options={'ordering': [models.Case(models.When(day_name='Monday', then=models.Value(1)), models.When(day_name='Tuesday', then=models.Value(2)), models.When(day_name='Wednesday', then=models.Value(3)), models.When(day_name='Thursday', then=models.Value(4)), models.When(day_name='Friday', then=models.Value(5)), models.When(day_name='Saturday', then=models.Value(6)), models.When(day_name='Sunday', then=models.Value(7)), output_field=models.IntegerField())]},
        ),
        migrations.AlterModelOptions(
            name='workoutday',
            options={'ordering': [models.Case(models.When(day_name='Monday', then=models.Value(1)), models.When(day_name='Tuesday', then=models.Value(2)), models.When(day_name='Wednesday', then=models.Value(3)), models.When(day_name='Thursday', then=models.Value(4)), models.When(day_name='Friday', then=models.Value(5)), models.When(day_name='Saturday', then=models.Value(6)), models.When(day_name='Sunday', then=models.Value(7)), output_field=models.IntegerField())]},
        ),
    ]
